services:
  netbox:
    ports:
    - 8050:8080
    volumes:
    - /mnt/backup/netbox:/etc/netbox/config:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z,rw
    - netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
  netbox-worker:
    volumes:
    - /mnt/backup/netbox:/etc/netbox/config:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z,rw
    - netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
  netbox-housekeeping:
    volumes:
    - /mnt/backup/netbox:/etc/netbox/config:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z,rw
    - netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
